### PR TITLE
 adding BGR ROI as sphere number 7

### PR DESCRIPTION
**Pull request by danieldeidda**

### CODE REVIEW

**Comment by KrisThielemans** [comment]
great. can you add some doc though?

**Comment by danieldeidda** [comment]
where?

**Comment by KrisThielemans** [comment]
in the docopt at the start, saying which sphere is which, and ideally also for the functions themselves. Something brief, but such that people have an idea what everything is without having to trawl through the details.

**Comment by KrisThielemans** [comment]
Thanks! I see a spurious L12 "subfolder of SIRF root folder" delete? Ideally also add some info on filenames, then I'll merge. Promised!

**Pull request merged**
